language: java
sudo: false
jdk:
- oraclejdk8
- oraclejdk9
before_install:
- chmod +x ./gradlew
script:
- ./gradlew check -i
- ./gradlew javadoc
- ./gradlew jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
